name: build

on:
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: run make docker-build
        run: make docker-build
